"""add username first_name last_name bio avatar_url

Revision ID: 17ec7d03f9bb
Revises: cdec1a0a3450
Create Date: 2026-01-11 19:41:41.248362

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17ec7d03f9bb"
down_revision: Union[str, Sequence[str], None] = "cdec1a0a3450"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename existing 'name' -> 'username' to preserve data
    op.alter_column(
        "users",
        "name",
        new_column_name="username",
        existing_type=sa.VARCHAR(length=100),
        existing_nullable=True,
    )

    # New columns
    op.add_column("users", sa.Column("first_name", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("bio", sa.String(length=500), nullable=True))
    op.add_column(
        "users", sa.Column("avatar_url", sa.String(length=2048), nullable=True)
    )

    # Ensure username is unique (note: existing duplicates would break migration)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")

    op.drop_column("users", "avatar_url")
    op.drop_column("users", "bio")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")

    # Rename back
    op.alter_column(
        "users",
        "username",
        new_column_name="name",
        existing_type=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
